#title: Les composés chimiques
SELECT ?compch ?compchlabel ?pe ?masse ?formule {
  ?compch wdt:P31 wd:Q11173. # composé chimique
  ?compch wdt:P2102 ?pe. # point d'ébullition
  ?compch wdt:P2067 ?masse. # masse
  ?compch wdt:P274 ?formule. #formule chimique
  
  ?compch rdfs:label ?compchlabel. # libellé en français
  FILTER(lang(?compchlabel) = "fr")
  FILTER(contains(?compchlabel, "H"))
}
LIMIT 100
